title: Credo Map
description:
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vQ9iu5ndfvir6t4duI5ZLHgL8_dPPLanMfKR-GHViIBvQpsYvo5LZeUIyxcm9JJEK5rKZ7ZRbQDLqWS/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#d2691e"
orderby: distance
